ci:
  autofix_commit_msg: "ci(pre-commit): auto fixes from pre-commit hooks"
  autoupdate_commit_msg: "ci(pre-commit): update pre-commit hooks"
repos: []
  - cspell
    - shellcheck
repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        files: \.(bash|sh|zsh)(\.tmpl)?$
        types:
          - text
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        stages:
          - pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
        exclude: ^tsconfig\.json$
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-yaml
        args:
          - --unsafe
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.0
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.8.0-1
    hooks:
      - id: shfmt
        files: \.(bash|sh|zsh)(\.tmpl)?$
        types:
          - text
        args:
          - --write
          - --simplify
          - --indent=2
          - --case-indent
          - --space-redirects
  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.4
    hooks:
      - id: fix-ligatures
      - id: fix-spaces
      - id: forbid-bidi-controls
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.4.0
    hooks:
      - id: cspell
