name: Repo Template

description: Repo Template

inputs:
  token:
    description: GitHub Token
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - uses: liblaf/repo/.github/actions/install@main
      with:
        npm: prettier
        other: pch
        pipx: pre-commit
    # https://github.com/actions/toolkit/issues/1035
    - run: cp "${{ github.action_path }}/common/.pre-commit-config.yaml" ".pre-commit-config.yaml"
      shell: bash
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: ${{ hashFiles('.pre-commit-config.yaml') }}
    - run: make --always-make --directory="${{ github.action_path }}" --file="init.mk" --jobs DEST_DIR="$(pwd)"
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
