name: Depedabot

on:
  pull_request:

jobs:
  merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |-
          body=$(gh pr view "$PR" --jq ".body" --json "body")
          if grep --quiet "$MESSAGE" <<< "$body"; then
            grep "$MESSAGE" <<< "$body"
          else
            gh pr comment "$PR" --body "@dependabot squash and merge"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          MESSAGE: Dependabot will merge this PR once CI passes on it
          PR: ${{ github.event.pull_request.number }}
