name: Release

description: Release

inputs:
  token:
    description: GitHub Token
    required: false
    default: ${{ github.token }}
  tag:
    description: Tag
    required: true
  files:
    description: Newline-delimited list of path globs for asset files to upload
    required: false
  pre-release:
    description: Mark the release as a prerelease
    required: false
    default: "false"
  repo:
    description: Select another repository using the [HOST/]OWNER/REPO format
    required: false
    default: ${{ github.repository }}
  algorithm:
    description: Compute checksums using the specified digest algorithm
    required: false
    default: b2sum
  recreate:
    description: Recreate the release if it already exists
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    # TODO: add changelog
    # - run: |-
    #     npm install conventional-changelog-conventionalcommits
    #     cp "${{ github.action_path }}/changelog-config.js" ./changelog-config.js
    #   shell: bash
    # - id: changelog
    #   uses: TriPSs/conventional-changelog-action@v5
    #   with:
    #     git-push: false
    #     output-file: false
    #     skip-version-file: true
    #     skip-commit: true
    #     skip-tag: true
    #     config-file-path: ./changelog-config.js
    #     create-summary: true
    #     skip-bump: true
    # - run: rm -r ./changelog-config.js
    #   shell: bash
    - run: bash "${{ github.action_path }}/main.sh"
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        TAG: ${{ inputs.tag }}
        FILES: ${{ inputs.files }}
        PRE_RELEASE: ${{ inputs.pre-release }}
        REPO: ${{ inputs.repo }}
        ALGORITHM: ${{ inputs.algorithm }}
        RECREATE: ${{ inputs.recreate }}
        # CHANGELOG: ${{ steps.changelog.outputs.clean_changelog }}
