name: Release

description: Release

inputs:
  token:
    description: GitHub Token
    required: false
    default: ${{ github.token }}
  repo:
    description: Select another repository using the [HOST/]OWNER/REPO format
    required: false
    default: ${{ github.repository }}
  tag:
    description: Tag
    required: true
  files:
    description: Newline-delimited list of path globs for asset files to upload
    required: false
  checksum:
    description: Compute checksums using the specified digest algorithm
    required: false
    default: blake2b
  pre-release:
    description: Mark the release as a prerelease
    required: false
    default: "false"
  recreate:
    description: Recreate the release if it already exists
    required: false
    default: "false"
  release-pr:
    description: A JSON string of the PullRequest object created by Release Please
    required: false

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: pip install 'https://github.com/liblaf/repo/releases/download/dev/liblaf_repo-0.0.0-py3-none-any.whl'
      shell: bash
      name: Install Tools
    - run: python -m repo.actions.release
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        INPUT_REPO: ${{ inputs.repo }}
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_FILES: ${{ inputs.files }}
        INPUT_CHECKSUM: ${{ inputs.checksum }}
        INPUT_PRE_RELEASE: ${{ inputs.pre-release }}
        INPUT_RECREATE: ${{ inputs.recreate }}
        INPUT_RELEASE_PR: ${{ inputs.release-pr }}
