name: Release

author: liblaf

description: Manage releases

inputs:
  algo:
    description: Compute hashsums using the specified digest algorithm
    required: false
    default: sha256
  clobber:
    description: Recreate the release if it already exists
    required: false
    default: "false"
  files:
    description: Newline-delimited list of path globs for asset files to upload
    required: false
  pre-release:
    description: Mark the release as a prerelease
    required: false
    default: "false"
  repo:
    description: owner/repo
    required: false
    default: ${{ github.repository }}
  tag:
    description: Tag name
    required: true
  token:
    description: GitHub token
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        path: _tmp.W8nAhH91eW
        fetch-depth: 0
    - run: |-
        npx conventional-changelog-cli --outfile "${{ runner.temp }}/CHANGELOG.md" --config "${{ github.action_path }}/changelog.json"
        npx prettier --write --ignore-path "" "${{ runner.temp }}/CHANGELOG.md"
      shell: bash
      name: Generate Changelog
      working-directory: _tmp.W8nAhH91eW
    - run: pipx --package git+https://github.com/liblaf/repo.git release
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        INPUT_ALGO: ${{ inputs.hashsum }}
        INPUT_CHANGELOG_FILE: ${{ runner.temp }}/CHANGELOG.md
        INPUT_CLOBBER: ${{ inputs.clobber }}
        INPUT_FILES: ${{ inputs.files }}
        INPUT_PRE_RELEASE: ${{ inputs.pre-release }}
        INPUT_REPO: ${{ github.repository }}
        INPUT_TAG: ${{ inputs.tag }}
      working-directory: _tmp.W8nAhH91eW
