name: Auto Merge Release Please

on:
  schedule:
    - cron: "0 0 * * 0" # Run weekly

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge Release Please
        uses: liblaf/action/auto-merge@main
