name: Install

description: Install

inputs:
  token:
    description: GitHub Token
    required: false
    default: ${{ github.token }}
  apt:
    description: "APT packages to install"
    required: false
    default: ""
  brew:
    description: "Brew packages to install"
    required: false
    default: ""
  choco:
    description: "Chocolatey packages to install"
    required: false
    default: ""
  other:
    description: "Other packages to install"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - run: bash "${{ github.action_path }}/scripts/apt.sh" ${{ inputs.apt }}
      shell: bash
      if: inputs.apt
    - run: bash "${{ github.action_path }}/scripts/brew.sh" ${{ inputs.brew }}
      shell: bash
      if: inputs.brew
    - run: bash "${{ github.action_path }}/scripts/choco.sh" ${{ inputs.choco }}
      shell: bash
      if: inputs.choco
    - run: bash "${{ github.action_path }}/scripts/other.sh" ${{ inputs.other }}
      shell: bash
      if: inputs.other
      env:
        GH_TOKEN: ${{ inputs.token }}
