name: pre-commit Update

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  update:
    name: Update
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Tools
        uses: liblaf/repo/.github/actions/install@main
        with:
          npm: prettier
          other: pch
      - name: Update
        run: pch update "common/.pre-commit-config.yaml"
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(pre-commit): update pre-commit hooks"
