name: Repo Template

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Tools
        uses: liblaf/repo/.github/actions/install@main
        with:
          other: pch
      - name: Sync
        run: bash "scripts/sync.sh"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
