name: Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      owner:
        required: false
        type: string
        default: liblaf
        description: The account owner of the repository. The name is not case sensitive.
      repo:
        required: false
        type: string
        default: repo
        description: The name of the repository without the .git extension. The name is not case sensitive.
      token:
        required: false
        type: string

env:
  FORCE_COLOR: 1

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - id: inputs
        name: Inputs
        run: |-
          echo "owner=${{ inputs.owner || github.repository_owner }}" >> "$GITHUB_OUTPUT"
          if [[ -n "${{ inputs.repo }}" ]]; then
            echo "repo=${{ inputs.repo }}" >> "$GITHUB_OUTPUT"
          else
            repo=$(echo "${{ github.repository }}" | cut --delimiter='/' --fields=2)
            echo "repo=$repo" >> "$GITHUB_OUTPUT"
          fi
          echo "token=${{ inputs.token || secrets.PAT || secrets.GH_TOKEN || github.token }}" >> "$GITHUB_OUTPUT"
      - name: Checkout Target
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.inputs.outputs.owner }}/${{ steps.inputs.outputs.repo }}
          token: ${{ steps.inputs.outputs.token }}
          path: target
      - name: Checkout Repository Template
        uses: actions/checkout@v4
        with:
          path: source
      - name: Install Tools
        uses: liblaf/repo/.github/actions/install@main
        with:
          eget: liblaf/pre-commit-hooks
          npm: prettier
          pipx: pre-commit
      - name: Cache pre-commit Hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ hashFiles('source/presets/common/.pre-commit-config.yaml') }}
      - name: Sync with Repository Template
        run: bash main.sh
        env:
          DEST_DIR: ${{ github.workspace }}/target
          GH_TOKEN: ${{ steps.inputs.outputs.token }}
          OWNER: ${{ steps.inputs.outputs.owner }}
          REPO: ${{ steps.inputs.outputs.repo }}
        working-directory: source/presets
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: |-
            chore(repo): sync with repository template

            template: <${{ github.server_url }}/${{ github.repository }}>
          repository: target
