name: Sync

on:
  workflow_dispatch:
    inputs:
      owner:
        required: true
        type: string
        default: liblaf
        description: The account owner of the repository. The name is not case sensitive.
      repo:
        required: true
        type: string
        default: repo
        description: The name of the repository without the .git extension. The name is not case sensitive.

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Template
        uses: actions/checkout@v4
        with:
          path: source
      - name: Checkout Target
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.owner }}/${{ inputs.repo }}
          token: ${{ secrets.GH_TOKEN }}
          path: target
      - name: Install Tools
        uses: liblaf/repo/.github/actions/install@main
        with:
          eget: liblaf/pre-commit-hooks
          npm: prettier
          pipx: pre-commit
      - name: Cache pre-commit Hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ hashFiles('source/presets/common/.pre-commit-config.yaml') }}
      - run: bash main.sh
        env:
          DESTDIR: ${{ github.workspace }}/target
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OWNER: ${{ inputs.owner }}
          REPO: ${{ inputs.repo }}
        working-directory: source/presets
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(repo): sync with repo template"
          repository: target
