name: Sync

on:
  workflow_dispatch:
    inputs:
      repo:
        description: GitHub Repository
        required: true
        type: string

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          token: ${{ secrets.GH_TOKEN }}
      - name: Sync
        uses: liblaf/repo@main
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(repo): sync with repo template"
