name: Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      owner:
        required: false
        type: string
        default: liblaf
        description: The account owner of the repository. The name is not case sensitive.
      repo:
        required: false
        type: string
        default: repo
        description: The name of the repository without the .git extension. The name is not case sensitive.

env:
  APP_ID: 1022004
  FORCE_COLOR: 1

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - id: inputs
        name: Prepare Inputs
        run: |-
          echo "owner=${{ inputs.owner || github.repository_owner }}" >> "$GITHUB_OUTPUT"
          if [[ -n "${{ inputs.repo }}" ]]; then
            echo "repo=${{ inputs.repo }}" >> "$GITHUB_OUTPUT"
          else
            repo=$(echo "${{ github.repository }}" | cut --delimiter='/' --fields=2)
            echo "repo=$repo" >> "$GITHUB_OUTPUT"
          fi
      - id: app-token
        name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ steps.inputs.outputs.owner }}
          repositories: ${{ steps.inputs.outputs.repo }}
      - id: get-user-id
        name: Get GitHub App User ID
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq '.id')" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - id: committer
        name: Get GitHub App Commiter
        run: echo "string=${{ steps.app-token.outputs.app-slug }}[bot] <${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>" >> "$GITHUB_OUTPUT"
      - name: Checkout Target
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.inputs.outputs.owner }}/${{ steps.inputs.outputs.repo }}
          token: ${{ steps.app-token.outputs.token }}
          path: target
      - name: Checkout Repository Template
        uses: actions/checkout@v4
        with:
          path: source
      - name: Install Tools
        uses: liblaf/actions/install@main
        with:
          eget: liblaf/pre-commit-hooks
          npm: prettier
          pipx: pre-commit
      - name: Cache pre-commit Hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ hashFiles('source/presets/common/.pre-commit-config.yaml') }}
      - name: Sync with Repository Template
        run: bash main.sh
        env:
          DEST_DIR: ${{ github.workspace }}/target
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          OWNER: ${{ steps.inputs.outputs.owner }}
          REPO: ${{ steps.inputs.outputs.repo }}
        working-directory: source/presets
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: |-
            chore(repo): sync with repository template

            template: <${{ github.server_url }}/${{ github.repository }}>
          repository: target
          commit_user_name: "${{ steps.app-token.outputs.app-slug }}[bot]"
          commit_user_email: "${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>"
          commit_author: ${{ steps.committer.outputs.string }}
