name: Sync All

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync All
        run: bash "scripts/sync-all.sh"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
